version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 112046827773.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 112046827773.dkr.ecr.ap-northeast-1.amazonaws.com/oio:latest .
      - docker tag 112046827773.dkr.ecr.ap-northeast-1.amazonaws.com/oio:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 112046827773.dkr.ecr.ap-northeast-1.amazonaws.com/oio:latest
      - printf '[{"name":"service","imageUri":"112046827773.dkr.ecr.ap-northeast-1.amazonaws.com/oio:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
  name: BuildService
